# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\cinema_gui\terminal_picker_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_terminal_picker(object):
    def setupUi(self, terminal_picker):
        terminal_picker.setObjectName("terminal_picker")
        terminal_picker.resize(480, 238)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(terminal_picker)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.term_pick_label = QtWidgets.QLabel(terminal_picker)
        self.term_pick_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.term_pick_label.setAlignment(QtCore.Qt.AlignCenter)
        self.term_pick_label.setObjectName("term_pick_label")
        self.verticalLayout.addWidget(self.term_pick_label)
        self.user_terminal_button = QtWidgets.QPushButton(terminal_picker)
        self.user_terminal_button.setObjectName("user_terminal_button")
        self.verticalLayout.addWidget(self.user_terminal_button)
        self.admin_terminal_button = QtWidgets.QPushButton(terminal_picker)
        self.admin_terminal_button.setObjectName("admin_terminal_button")
        self.verticalLayout.addWidget(self.admin_terminal_button)
        self.aboutButton = QtWidgets.QPushButton(terminal_picker)
        self.aboutButton.setObjectName("aboutButton")
        self.verticalLayout.addWidget(self.aboutButton)
        self.aboutTextBrowser = QtWidgets.QTextBrowser(terminal_picker)
        self.aboutTextBrowser.setObjectName("aboutTextBrowser")
        self.verticalLayout.addWidget(self.aboutTextBrowser)
        self.backButton = QtWidgets.QPushButton(terminal_picker)
        self.backButton.setObjectName("backButton")
        self.verticalLayout.addWidget(self.backButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(terminal_picker)
        QtCore.QMetaObject.connectSlotsByName(terminal_picker)

    def retranslateUi(self, terminal_picker):
        _translate = QtCore.QCoreApplication.translate
        terminal_picker.setWindowTitle(_translate("terminal_picker", "Выбор терминала"))
        self.term_pick_label.setText(_translate("terminal_picker", "Выберите терминал"))
        self.user_terminal_button.setToolTip(_translate("terminal_picker", "Покупка билетов на сеанс"))
        self.user_terminal_button.setText(_translate("terminal_picker", "Пользоватльский терминал"))
        self.admin_terminal_button.setToolTip(_translate("terminal_picker", "Редактирование информации о сеансах"))
        self.admin_terminal_button.setText(_translate("terminal_picker", "Терминал администратора"))
        self.aboutButton.setText(_translate("terminal_picker", "О программе"))
        self.backButton.setText(_translate("terminal_picker", "Назад к выбору терминала"))
