# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\cinema_gui\user_terminal_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserTerminal(object):
    def setupUi(self, UserTerminal):
        UserTerminal.setObjectName("UserTerminal")
        UserTerminal.resize(744, 535)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(UserTerminal.sizePolicy().hasHeightForWidth())
        UserTerminal.setSizePolicy(sizePolicy)
        UserTerminal.setAutoFillBackground(True)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(UserTerminal)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.sessionsTextBrowser = QtWidgets.QTextBrowser(UserTerminal)
        self.sessionsTextBrowser.setEnabled(True)
        self.sessionsTextBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.sessionsTextBrowser.setObjectName("sessionsTextBrowser")
        self.verticalLayout.addWidget(self.sessionsTextBrowser)
        self.sessionPickLabel = QtWidgets.QLabel(UserTerminal)
        self.sessionPickLabel.setObjectName("sessionPickLabel")
        self.verticalLayout.addWidget(self.sessionPickLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sessionEdit = QtWidgets.QLineEdit(UserTerminal)
        self.sessionEdit.setObjectName("sessionEdit")
        self.verticalLayout_2.addWidget(self.sessionEdit)
        self.placeLabel = QtWidgets.QLabel(UserTerminal)
        self.placeLabel.setObjectName("placeLabel")
        self.verticalLayout_2.addWidget(self.placeLabel)
        self.placeEdit = QtWidgets.QLineEdit(UserTerminal)
        self.placeEdit.setObjectName("placeEdit")
        self.verticalLayout_2.addWidget(self.placeEdit)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buyButton = QtWidgets.QPushButton(UserTerminal)
        self.buyButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buyButton.sizePolicy().hasHeightForWidth())
        self.buyButton.setSizePolicy(sizePolicy)
        self.buyButton.setMaximumSize(QtCore.QSize(75, 16777215))
        self.buyButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.buyButton.setObjectName("buyButton")
        self.horizontalLayout.addWidget(self.buyButton)
        self.toBuyButton = QtWidgets.QPushButton(UserTerminal)
        self.toBuyButton.setObjectName("toBuyButton")
        self.horizontalLayout.addWidget(self.toBuyButton)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.nextIterLayout = QtWidgets.QVBoxLayout()
        self.nextIterLayout.setObjectName("nextIterLayout")
        self.nextIterLabel = QtWidgets.QLabel(UserTerminal)
        self.nextIterLabel.setObjectName("nextIterLabel")
        self.nextIterLayout.addWidget(self.nextIterLabel)
        self.yesNoHorizontalLayout = QtWidgets.QHBoxLayout()
        self.yesNoHorizontalLayout.setObjectName("yesNoHorizontalLayout")
        self.yesButton = QtWidgets.QPushButton(UserTerminal)
        self.yesButton.setObjectName("yesButton")
        self.yesNoHorizontalLayout.addWidget(self.yesButton)
        self.noButton = QtWidgets.QPushButton(UserTerminal)
        self.noButton.setObjectName("noButton")
        self.yesNoHorizontalLayout.addWidget(self.noButton)
        self.nextIterLayout.addLayout(self.yesNoHorizontalLayout)
        self.verticalLayout.addLayout(self.nextIterLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout)

        self.retranslateUi(UserTerminal)
        QtCore.QMetaObject.connectSlotsByName(UserTerminal)

    def retranslateUi(self, UserTerminal):
        _translate = QtCore.QCoreApplication.translate
        UserTerminal.setWindowTitle(_translate("UserTerminal", "Терминал пользователя"))
        self.sessionPickLabel.setText(_translate("UserTerminal", "Ввведите id сеанса на который хотите купить билет"))
        self.placeLabel.setText(_translate("UserTerminal", "Введите место"))
        self.buyButton.setText(_translate("UserTerminal", "Купить"))
        self.toBuyButton.setText(_translate("UserTerminal", "Перейти к покупке"))
        self.nextIterLabel.setText(_translate("UserTerminal", "Желаете купить еще билет?"))
        self.yesButton.setText(_translate("UserTerminal", "Да!"))
        self.noButton.setText(_translate("UserTerminal", "Нет("))
